# join,concatinatio,merge,numericals

In [1]:
import pandas as pd

In [2]:
data = {'name' : ['Shubhangi','soname','punam','Rahul'],
       'salary' : [100,200,300,400],
       'mail_id' : ['shu@123.com','son@123.com','pun@123.com','ra@123.com'],
       'addr' : ['MH','MH','MH','MH']}

In [3]:
data

{'name': ['Shubhangi', 'soname', 'punam', 'Rahul'],
 'salary': [100, 200, 300, 400],
 'mail_id': ['shu@123.com', 'son@123.com', 'pun@123.com', 'ra@123.com'],
 'addr': ['MH', 'MH', 'MH', 'MH']}

In [4]:
df = pd.DataFrame(data) # dict to dataframe ,key-col and values - rows
#list values must be same
#pd.DataFrame(data,columns=) if key not there

In [13]:
 df = pd.DataFrame(data , index=[0,1,2,3])  # own index values

In [14]:
df.loc[1:3]    #extract rows

name  salary      mail_id addr
1  soname     200  son@123.com   MH
2   punam     300  pun@123.com   MH
3   Rahul     400   ra@123.com   MH

In [15]:
df.iloc[1:3] #iloc go to look after default indexs (internal index that we already have)

name  salary      mail_id addr
1  soname     200  son@123.com   MH
2   punam     300  pun@123.com   MH

In [16]:
data1 = {'pf_num' : [234,564,231,5465],
        'income_tax' : [123,34,54,2234],
        'mobile_no' : [2342,543,454,5652],
        'courses' : ['ds','bigdata','web','processing']
        }

In [17]:
df1 = pd.DataFrame(data1)

In [18]:
df1

pf_num  income_tax  mobile_no     courses
0     234         123       2342          ds
1     564          34        543     bigdata
2     231          54        454         web
3    5465        2234       5652  processing

In [20]:
pd.concat([df,df1])   #vertical concatination (bcz column names are different)

name  salary      mail_id addr  pf_num  income_tax  mobile_no  \
0  Shubhangi   100.0  shu@123.com   MH     NaN         NaN        NaN   
1     soname   200.0  son@123.com   MH     NaN         NaN        NaN   
2      punam   300.0  pun@123.com   MH     NaN         NaN        NaN   
3      Rahul   400.0   ra@123.com   MH     NaN         NaN        NaN   
0        NaN     NaN          NaN  NaN   234.0       123.0     2342.0   
1        NaN     NaN          NaN  NaN   564.0        34.0      543.0   
2        NaN     NaN          NaN  NaN   231.0        54.0      454.0   
3        NaN     NaN          NaN  NaN  5465.0      2234.0     5652.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2         web  
3  processing

In [23]:
pd.concat([df,df1], axis=1) #horizontal concat

name  salary      mail_id addr  pf_num  income_tax  mobile_no  \
0  Shubhangi     100  shu@123.com   MH     234         123       2342   
1     soname     200  son@123.com   MH     564          34        543   
2      punam     300  pun@123.com   MH     231          54        454   
3      Rahul     400   ra@123.com   MH    5465        2234       5652   

      courses  
0          ds  
1     bigdata  
2         web  
3  processing

# If column name are same then:

In [35]:
data2 = {'0' : ['Shubhangi','soname','punam','Rahul'],
       '1' : [100,200,300,400],
       '2' : ['shu@123.com','son@123.com','pun@123.com','ra@123.com'],
       '3' : ['MH','MH','MH','MH']}

In [36]:
data3 = {'0' : [234,564,231,5465],
        '1' : [123,34,54,2234],
        '2' : [2342,543,454,5652],
        '3' : ['ds','bigdata','web','processing']
        }

In [37]:
df2 = pd.DataFrame(data2)

In [38]:
df2

0    1            2   3
0  Shubhangi  100  shu@123.com  MH
1     soname  200  son@123.com  MH
2      punam  300  pun@123.com  MH
3      Rahul  400   ra@123.com  MH

In [39]:
df3 = pd.DataFrame(data3)

In [40]:
df3

0     1     2           3
0   234   123  2342          ds
1   564    34   543     bigdata
2   231    54   454         web
3  5465  2234  5652  processing

In [41]:
pd.concat([df2,df3]) # data arange verticaly

0     1            2           3
0  Shubhangi   100  shu@123.com          MH
1     soname   200  son@123.com          MH
2      punam   300  pun@123.com          MH
3      Rahul   400   ra@123.com          MH
0        234   123         2342          ds
1        564    34          543     bigdata
2        231    54          454         web
3       5465  2234         5652  processing

# merge()

In [42]:
data4 = {'emp_id' : [101,102,103,104],
        'salary' : [654,432,200,433],
        'pf' : [32,45,23,23]}

In [44]:
data5 = {'emp_id' : [101,102,104,105],
        'mob_no' : [22132,34322,45673,12312],
        'house_nu' : [345,345,345,56]}

In [45]:
df4 = pd.DataFrame(data4)

In [46]:
df4

emp_id  salary  pf
0     101     654  32
1     102     432  45
2     103     200  23
3     104     433  23

In [47]:
df5 = pd.DataFrame(data5)

In [48]:
df5

emp_id  mob_no  house_nu
0     101   22132       345
1     102   34322       345
2     104   45673       345
3     105   12312        56

In [49]:
pd.merge(df4,df5) #bydefault find comman values, whatever comman data we have W.R.T comman columns are there

emp_id  salary  pf  mob_no  house_nu
0     101     654  32   22132       345
1     102     432  45   34322       345
2     104     433  23   45673       345

In [50]:
pd.merge(df4,df5, how='right', on  = 'emp_id')

emp_id  salary    pf  mob_no  house_nu
0     101   654.0  32.0   22132       345
1     102   432.0  45.0   34322       345
2     104   433.0  23.0   45673       345
3     105     NaN   NaN   12312        56

In [55]:
data6 = {'emp_id1' : [101,102,103,104],
        'salary' : [234, 345, 564, 400],
        'pf' : [23,34,56,12]}

data7 = {'emp_id2' : [101,102,104,105],
        'mob_no' : [1212,3434,4545,8787],
        'house_no' : [232,343,565,787]
        }
#if comman col not there then it not merge

In [56]:
df6 = pd.DataFrame(data6)

In [57]:
df7 = pd.DataFrame(data7)

In [59]:
pd.merge(df6,df7, left_on='emp_id1', right_on='emp_id2', how = 'inner') # inner bydefault

emp_id1  salary  pf  emp_id2  mob_no  house_no
0      101     234  23      101    1212       232
1      102     345  34      102    3434       343
2      104     400  12      104    4545       565

In [60]:
data8 = {'emp_id' : [101,102,103,104],
        'salary' : [234, 345, 564, 400],
        'pf' : [23,34,56,12]}

data9 = {'emp_id' : [101,102,104,105],
        'salary' : [234, 345, 564, 400],
        'house_no' : [232,343,565,787]
        }
#if comman col not there then it not merge

In [61]:
df8 = pd.DataFrame(data8)

In [62]:
df9 = pd.DataFrame(data9)

In [64]:
pd.merge(df8,df9,on = ['emp_id' , 'salary']) #check both col comman values if match then give output

emp_id  salary  pf  house_no
0     101     234  23       232
1     102     345  34       343

In [74]:
#dimentions of dataframes are not same here
data10 = {'emp_id1' : [101,102,103,104],
        'salary1' : [234, 345, 564, 400],
        'pf' : [23,34,56,12]}

data11 = {'emp_id2' : [101,102,104,105,321],
        'salary2' : [234, 345, 564, 400, 45],
        'house_no' : [232,343,565,787, 234]
        }


In [75]:
df10 = pd.DataFrame(data10, index = ['a','b','c','d'])

In [76]:
df11 = pd.DataFrame(data11, index = ['a','b','d','e','f'])

In [77]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      564  56
d      104      400  12

In [78]:
df11

emp_id2  salary2  house_no
a      101      234       232
b      102      345       343
d      104      564       565
e      105      400       787
f      321       45       234

In [79]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_no
a      101      234  23    101.0    234.0     232.0
b      102      345  34    102.0    345.0     343.0
c      103      564  56      NaN      NaN       NaN
d      104      400  12    104.0    564.0     565.0

In [82]:
df_sales=pd.read_csv('D:/AllFam/ML/pandas/sales-data-sample.csv')

In [83]:
df_sales.head()

OrderDate         Category          City        Country  \
0  2011-01-04T00:00:00.000Z  Office Supplies       Houston  United States   
1  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
2  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
3  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
4  2011-01-06T00:00:00.000Z  Office Supplies  Philadelphia  United States   

    CustomerName  Discount         OrderID  PostalCode  \
0  Darren Powers       0.2  CA-2011-103800       77095   
1  Phillina Ober       0.2  CA-2011-112326       60540   
2  Phillina Ober       0.8  CA-2011-112326       60540   
3  Phillina Ober       0.2  CA-2011-112326       60540   
4     Mick Brown       0.2  CA-2011-141817       19143   

                                         ProductName  Profit  ...  \
0  Message Book, Wirebound, Four 5 1/2 X 4 Forms/...       6  ...   
1                                          Avery 508       4  ...   
2         GBC Standard Plastic Binding Systems Combs      -5  ...   
3                      SAFCO Boltless Steel Shelving     -65  ...   
4  Avery Hi-Liter EverBold Pen Style Fluorescent ...       5  ...   

   DaystoShipActual SalesForecast     ShipStatus DaystoShipScheduled  \
0                 4            22  Shipped Early                   6   
1                 4            15  Shipped Early                   6   
2                 4             5  Shipped Early                   6   
3                 4           357  Shipped Early                   6   
4                 7            26   Shipped Late                   6   

  OrderProfitable SalesperCustomer ProfitRatio SalesaboveTarget  latitude  \
0             NaN            16.45        33.8              NaN   29.8941   
1             NaN            11.78        36.3              NaN   41.7662   
2             NaN             3.54      -155.0              NaN   41.7662   
3             NaN           272.74       -23.8              NaN   41.7662   
4             NaN            19.54        25.0              NaN   39.9448   

   longitude  
0   -95.6481  
1   -88.1410  
2   -88.1410  
3   -88.1410  
4   -75.2288  

[5 rows x 28 columns]

In [81]:
def profit_flag(a):
    if a>=0:
        return "Positive"
    else:
        return "negative"

In [86]:
df_sales['profit_flag'] = df_sales['Profit'].apply(profit_flag)   # user define method we can apply

In [87]:
df_sales.head()

OrderDate         Category          City        Country  \
0  2011-01-04T00:00:00.000Z  Office Supplies       Houston  United States   
1  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
2  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
3  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
4  2011-01-06T00:00:00.000Z  Office Supplies  Philadelphia  United States   

    CustomerName  Discount         OrderID  PostalCode  \
0  Darren Powers       0.2  CA-2011-103800       77095   
1  Phillina Ober       0.2  CA-2011-112326       60540   
2  Phillina Ober       0.8  CA-2011-112326       60540   
3  Phillina Ober       0.2  CA-2011-112326       60540   
4     Mick Brown       0.2  CA-2011-141817       19143   

                                         ProductName  Profit  ...  \
0  Message Book, Wirebound, Four 5 1/2 X 4 Forms/...       6  ...   
1                                          Avery 508       4  ...   
2         GBC Standard Plastic Binding Systems Combs      -5  ...   
3                      SAFCO Boltless Steel Shelving     -65  ...   
4  Avery Hi-Liter EverBold Pen Style Fluorescent ...       5  ...   

   SalesForecast     ShipStatus  DaystoShipScheduled OrderProfitable  \
0             22  Shipped Early                    6             NaN   
1             15  Shipped Early                    6             NaN   
2              5  Shipped Early                    6             NaN   
3            357  Shipped Early                    6             NaN   
4             26   Shipped Late                    6             NaN   

  SalesperCustomer ProfitRatio SalesaboveTarget latitude  longitude  \
0            16.45        33.8              NaN  29.8941   -95.6481   
1            11.78        36.3              NaN  41.7662   -88.1410   
2             3.54      -155.0              NaN  41.7662   -88.1410   
3           272.74       -23.8              NaN  41.7662   -88.1410   
4            19.54        25.0              NaN  39.9448   -75.2288   

   profit_flag  
0     Positive  
1     Positive  
2     negative  
3     negative  
4     Positive  

[5 rows x 29 columns]

In [88]:
df['cus_name_len'] =df_sales['CustomerName'].apply(len)

In [89]:
df_sales.head()

OrderDate         Category          City        Country  \
0  2011-01-04T00:00:00.000Z  Office Supplies       Houston  United States   
1  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
2  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
3  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
4  2011-01-06T00:00:00.000Z  Office Supplies  Philadelphia  United States   

    CustomerName  Discount         OrderID  PostalCode  \
0  Darren Powers       0.2  CA-2011-103800       77095   
1  Phillina Ober       0.2  CA-2011-112326       60540   
2  Phillina Ober       0.8  CA-2011-112326       60540   
3  Phillina Ober       0.2  CA-2011-112326       60540   
4     Mick Brown       0.2  CA-2011-141817       19143   

                                         ProductName  Profit  ...  \
0  Message Book, Wirebound, Four 5 1/2 X 4 Forms/...       6  ...   
1                                          Avery 508       4  ...   
2         GBC Standard Plastic Binding Systems Combs      -5  ...   
3                      SAFCO Boltless Steel Shelving     -65  ...   
4  Avery Hi-Liter EverBold Pen Style Fluorescent ...       5  ...   

   SalesForecast     ShipStatus  DaystoShipScheduled OrderProfitable  \
0             22  Shipped Early                    6             NaN   
1             15  Shipped Early                    6             NaN   
2              5  Shipped Early                    6             NaN   
3            357  Shipped Early                    6             NaN   
4             26   Shipped Late                    6             NaN   

  SalesperCustomer ProfitRatio SalesaboveTarget latitude  longitude  \
0            16.45        33.8              NaN  29.8941   -95.6481   
1            11.78        36.3              NaN  41.7662   -88.1410   
2             3.54      -155.0              NaN  41.7662   -88.1410   
3           272.74       -23.8              NaN  41.7662   -88.1410   
4            19.54        25.0              NaN  39.9448   -75.2288   

   profit_flag  
0     Positive  
1     Positive  
2     negative  
3     negative  
4     Positive  

[5 rows x 29 columns]

In [92]:
def quantity_flag(a):
    if a < 10:
        return 'low'
    elif a>10 and a<20:
        return 'Medium'
    else:
        return 'high'

In [94]:
df_sales['flag_quantity'] = df_sales['Quantity'].apply(quantity_flag)

In [95]:
df_sales.head()

OrderDate         Category          City        Country  \
0  2011-01-04T00:00:00.000Z  Office Supplies       Houston  United States   
1  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
2  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
3  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
4  2011-01-06T00:00:00.000Z  Office Supplies  Philadelphia  United States   

    CustomerName  Discount         OrderID  PostalCode  \
0  Darren Powers       0.2  CA-2011-103800       77095   
1  Phillina Ober       0.2  CA-2011-112326       60540   
2  Phillina Ober       0.8  CA-2011-112326       60540   
3  Phillina Ober       0.2  CA-2011-112326       60540   
4     Mick Brown       0.2  CA-2011-141817       19143   

                                         ProductName  Profit  ...  \
0  Message Book, Wirebound, Four 5 1/2 X 4 Forms/...       6  ...   
1                                          Avery 508       4  ...   
2         GBC Standard Plastic Binding Systems Combs      -5  ...   
3                      SAFCO Boltless Steel Shelving     -65  ...   
4  Avery Hi-Liter EverBold Pen Style Fluorescent ...       5  ...   

      ShipStatus DaystoShipScheduled  OrderProfitable SalesperCustomer  \
0  Shipped Early                   6              NaN            16.45   
1  Shipped Early                   6              NaN            11.78   
2  Shipped Early                   6              NaN             3.54   
3  Shipped Early                   6              NaN           272.74   
4   Shipped Late                   6              NaN            19.54   

  ProfitRatio SalesaboveTarget latitude longitude  profit_flag  flag_quantity  
0        33.8              NaN  29.8941  -95.6481     Positive            low  
1        36.3              NaN  41.7662  -88.1410     Positive            low  
2      -155.0              NaN  41.7662  -88.1410     negative            low  
3       -23.8              NaN  41.7662  -88.1410     negative            low  
4        25.0              NaN  39.9448  -75.2288     Positive            low  

[5 rows x 30 columns]

In [96]:
df_sales['square_quantity'] = df_sales['Quantity'].apply(lambda a : a**2)

In [97]:
df_sales.head()

OrderDate         Category          City        Country  \
0  2011-01-04T00:00:00.000Z  Office Supplies       Houston  United States   
1  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
2  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
3  2011-01-05T00:00:00.000Z  Office Supplies    Naperville  United States   
4  2011-01-06T00:00:00.000Z  Office Supplies  Philadelphia  United States   

    CustomerName  Discount         OrderID  PostalCode  \
0  Darren Powers       0.2  CA-2011-103800       77095   
1  Phillina Ober       0.2  CA-2011-112326       60540   
2  Phillina Ober       0.8  CA-2011-112326       60540   
3  Phillina Ober       0.2  CA-2011-112326       60540   
4     Mick Brown       0.2  CA-2011-141817       19143   

                                         ProductName  Profit  ...  \
0  Message Book, Wirebound, Four 5 1/2 X 4 Forms/...       6  ...   
1                                          Avery 508       4  ...   
2         GBC Standard Plastic Binding Systems Combs      -5  ...   
3                      SAFCO Boltless Steel Shelving     -65  ...   
4  Avery Hi-Liter EverBold Pen Style Fluorescent ...       5  ...   

   DaystoShipScheduled OrderProfitable  SalesperCustomer ProfitRatio  \
0                    6             NaN             16.45        33.8   
1                    6             NaN             11.78        36.3   
2                    6             NaN              3.54      -155.0   
3                    6             NaN            272.74       -23.8   
4                    6             NaN             19.54        25.0   

  SalesaboveTarget latitude longitude profit_flag  flag_quantity  \
0              NaN  29.8941  -95.6481    Positive            low   
1              NaN  41.7662  -88.1410    Positive            low   
2              NaN  41.7662  -88.1410    negative            low   
3              NaN  41.7662  -88.1410    negative            low   
4              NaN  39.9448  -75.2288    Positive            low   

   square_quantity  
0                4  
1                9  
2                4  
3                9  
4                9  

[5 rows x 31 columns]

# importing Numpy

In [98]:
import numpy as np

In [99]:
np.array([2,3,4,5,6,7]) #one-D array

array([2. , 3. , 4. , 5. , 6.7])

In [100]:
type(np.array([2,3,4,5,6,7]))

numpy.ndarray

In [104]:
np.array([[2,3,4],[4,5,6]]) #2-D array , col - rep. as x-axis .. and row - rep. as y-axis

array([[2, 3, 4],
       [4, 5, 6]])

In [106]:
i = [[1,2,33,4],[4,6,7,8]]

In [107]:
i[0][1]

2

In [110]:
i = np.array([3,4,5,6], ndmin = 3)
i

array([[[3, 4, 5, 6]]])

In [112]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
arr.ndim

2

In [114]:
np.random.randint(1,10,(4,4)) # responsible to create random int 4-D array betwn 1-10

array([[8, 2, 4, 7],
       [8, 5, 5, 5],
       [5, 7, 6, 7],
       [4, 9, 8, 7]])

In [119]:
np.random.randint(1,10,(4,4,2))  #(z , y , x) => 4 -> (4 * 2) array
#like layers one after another(here 4 layer)
#e.g. rep. array in 3D is like inside book there are pages one after the other (here consider that array like a book and inside it some pages are there)

array([[[8, 3],
        [1, 7],
        [5, 1],
        [4, 4]],

       [[2, 1],
        [2, 7],
        [9, 2],
        [6, 2]],

       [[3, 7],
        [1, 2],
        [9, 5],
        [9, 6]],

       [[6, 7],
        [7, 4],
        [5, 3],
        [6, 2]]])